foxglove_enabled: False

microROS_enabled: False

drive_enabled: True

microROS:
  port_number: 9999

drive:
  drive_mode: TANK_STEER_HYBRID
  wait_until_positioned: False   # must be False when drive mode is TANK_STEER_HYBRID
  vesc_controller_enabled: True
  can_rate: 10
  can_channel: can0