# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - arm_base_joint
      - arm_shoulder_joint
      - arm_elbow_joint
      - arm_wrist_joint
      - gripper_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity