# This config file is used by ros2_control
arm/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      ros__parameters:
        use_local_topics: true

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm/arm_controller:
  ros__parameters:
    joints:
      - arm_base_joint
      - arm_shoulder_joint
      - arm_elbow_joint
      - arm_wrist_joint
      - gripper_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity