controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    drive_module_steering_angle_controller:
      type: position_controllers/JointGroupPositionController

    drive_module_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

drive_module_steering_angle_controller:
  ros__parameters:
    joints:
      - front_left_swerve_joint
      - front_right_swerve_joint
      - rear_left_swerve_joint
      - rear_right_swerve_joint

drive_module_velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint